'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Asiento
    Public Property IIDASIENTO As Integer
    Public Property IIDVIAJE As Nullable(Of Integer)
    Public Property INDICEFILA As Nullable(Of Integer)
    Public Property INDICECOLUMNA As Nullable(Of Integer)
    Public Property BHABILITADO As Nullable(Of Integer)

    Public Overridable Property Viaje As Viaje

End Class
