'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Cliente
    Public Property IIDCLIENTE As Integer
    Public Property NOMBRE As String
    Public Property APPATERNO As String
    Public Property APMATERNO As String
    Public Property EMAIL As String
    Public Property DIRECCION As String
    Public Property IIDSEXO As Nullable(Of Integer)
    Public Property TELEFONOFIJO As String
    Public Property TELEFONOCELULAR As String
    Public Property BHABILITADO As Nullable(Of Integer)
    Public Property bTieneUsuario As Nullable(Of Integer)
    Public Property TIPOUSUARIO As String

    Public Overridable Property Sexo As Sexo
    Public Overridable Property TIPOUSUARIOREGISTRO As TIPOUSUARIOREGISTRO
    Public Overridable Property VENTA As ICollection(Of VENTA) = New HashSet(Of VENTA)

End Class
