'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class BDPasajeEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=BDPasajeEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Asiento() As DbSet(Of Asiento)
    Public Overridable Property Bus() As DbSet(Of Bus)
    Public Overridable Property Cliente() As DbSet(Of Cliente)
    Public Overridable Property DETALLEVENTA() As DbSet(Of DETALLEVENTA)
    Public Overridable Property Empleado() As DbSet(Of Empleado)
    Public Overridable Property Lugar() As DbSet(Of Lugar)
    Public Overridable Property Marca() As DbSet(Of Marca)
    Public Overridable Property Modelo() As DbSet(Of Modelo)
    Public Overridable Property Pagina() As DbSet(Of Pagina)
    Public Overridable Property Rol() As DbSet(Of Rol)
    Public Overridable Property RolPagina() As DbSet(Of RolPagina)
    Public Overridable Property Sexo() As DbSet(Of Sexo)
    Public Overridable Property Sucursal() As DbSet(Of Sucursal)
    Public Overridable Property sysdiagrams() As DbSet(Of sysdiagrams)
    Public Overridable Property TipoBus() As DbSet(Of TipoBus)
    Public Overridable Property TipoContrato() As DbSet(Of TipoContrato)
    Public Overridable Property TipoUsuario() As DbSet(Of TipoUsuario)
    Public Overridable Property TIPOUSUARIOREGISTRO() As DbSet(Of TIPOUSUARIOREGISTRO)
    Public Overridable Property Usuario() As DbSet(Of Usuario)
    Public Overridable Property VENTA() As DbSet(Of VENTA)
    Public Overridable Property Viaje() As DbSet(Of Viaje)

End Class
