'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class DETALLEVENTA
    Public Property IIDETALLEVENTA As Integer
    Public Property IIDVENTA As Nullable(Of Integer)
    Public Property IIDVIAJE As Nullable(Of Integer)
    Public Property IIDBUS As Nullable(Of Integer)
    Public Property PRECIO As Nullable(Of Decimal)
    Public Property BHABILITADO As Nullable(Of Integer)

    Public Overridable Property Bus As Bus
    Public Overridable Property VENTA As VENTA
    Public Overridable Property Viaje As Viaje

End Class
