'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Empleado
    Public Property IIDEMPLEADO As Integer
    Public Property NOMBRE As String
    Public Property APPATERNO As String
    Public Property APMATERNO As String
    Public Property FECHACONTRATO As Nullable(Of Date)
    Public Property SUELDO As Nullable(Of Decimal)
    Public Property IIDTIPOUSUARIO As Nullable(Of Integer)
    Public Property IIDTIPOCONTRATO As Nullable(Of Integer)
    Public Property IIDSEXO As Nullable(Of Integer)
    Public Property BHABILITADO As Nullable(Of Integer)
    Public Property bTieneUsuario As Nullable(Of Integer)
    Public Property TIPOUSUARIO As String

    Public Overridable Property Sexo As Sexo
    Public Overridable Property TipoUsuario1 As TipoUsuario
    Public Overridable Property TipoContrato As TipoContrato
    Public Overridable Property TIPOUSUARIOREGISTRO As TIPOUSUARIOREGISTRO

End Class
