'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Rol
    Public Property IIDROL As Integer
    Public Property NOMBRE As String
    Public Property DESCRIPCION As String
    Public Property BHABILITADO As Nullable(Of Integer)

    Public Overridable Property RolPagina As ICollection(Of RolPagina) = New HashSet(Of RolPagina)
    Public Overridable Property Usuario As ICollection(Of Usuario) = New HashSet(Of Usuario)

End Class
