'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class RolPagina
    Public Property IIDROLPAGINA As Integer
    Public Property IIDROL As Nullable(Of Integer)
    Public Property IIDPAGINA As Nullable(Of Integer)
    Public Property BHABILITADO As Nullable(Of Integer)

    Public Overridable Property Pagina As Pagina
    Public Overridable Property Rol As Rol

End Class
