'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Sexo
    Public Property IIDSEXO As Integer
    Public Property NOMBRE As String
    Public Property BHABILITADO As Nullable(Of Integer)

    Public Overridable Property Cliente As ICollection(Of Cliente) = New HashSet(Of Cliente)
    Public Overridable Property Empleado As ICollection(Of Empleado) = New HashSet(Of Empleado)

End Class
