'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Usuario
    Public Property IIDUSUARIO As Integer
    Public Property NOMBREUSUARIO As String
    Public Property CONTRA As String
    Public Property TIPOUSUARIO As String
    Public Property IID As Nullable(Of Integer)
    Public Property IIDROL As Nullable(Of Integer)
    Public Property bhabilitado As Nullable(Of Integer)

    Public Overridable Property Rol As Rol
    Public Overridable Property TIPOUSUARIOREGISTRO As TIPOUSUARIOREGISTRO

End Class
