'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class VENTA
    Public Property IIDVENTA As Integer
    Public Property IIDCLIENTE As Nullable(Of Integer)
    Public Property TOTAL As Nullable(Of Decimal)
    Public Property FECHAVENTA As Nullable(Of Date)
    Public Property BHABILITADO As Nullable(Of Integer)

    Public Overridable Property Cliente As Cliente
    Public Overridable Property DETALLEVENTA As ICollection(Of DETALLEVENTA) = New HashSet(Of DETALLEVENTA)

End Class
