'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Viaje
    Public Property IIDVIAJE As Integer
    Public Property IIDLUGARORIGEN As Nullable(Of Integer)
    Public Property IIDLUGARDESTINO As Nullable(Of Integer)
    Public Property PRECIO As Nullable(Of Decimal)
    Public Property FECHAVIAJE As Nullable(Of Date)
    Public Property IIDBUS As Nullable(Of Integer)
    Public Property NUMEROASIENTOSDISPONIBLES As Nullable(Of Integer)
    Public Property BHABILITADO As Nullable(Of Integer)
    Public Property FOTO As Byte()
    Public Property nombrefoto As String

    Public Overridable Property Asiento As ICollection(Of Asiento) = New HashSet(Of Asiento)
    Public Overridable Property Bus As Bus
    Public Overridable Property DETALLEVENTA As ICollection(Of DETALLEVENTA) = New HashSet(Of DETALLEVENTA)
    Public Overridable Property Lugar As Lugar
    Public Overridable Property Lugar1 As Lugar

End Class
